export default {
  SYNC_BASE: {
    EVENT: 'SYNC_BASE',
    SYNC_THEME: 'SYNC_THEME',
  },
  SYNC_HOME_PAGE: {
    EVENT: 'SYNC_HOME_PAGE',
    FROM_CUSTOM_PAGE: 'SYNC_HOME_PAGE_FROM_CUSTOM_PAGE',
    FROM_SEARCH_PAGE: 'SYNC_HOME_PAGE_FROM_SEARCH_PAGE',
  },
  SYNC_POPULAR_PAGE: 'SYNC_POPULAR_PAGE',
  SYNC_TRENDING_PAGE: 'SYNC_POPULAR_PAGE',
  SYNC_FAVORITE_PAGE_POPULAR: 'SYNC_FAVORITE_PAGE_POPULAR',
  SYNC_FAVORITE_PAGE_TRENDING: 'SYNC_FAVORITE_PAGE_TRENDING',
}
