export default {
  SYNC_HOME_PAGE: 'SYNC_HOME_PAGE',
  SYNC_POPULAR_PAGE: 'SYNC_POPULAR_PAGE',
  SYNC_TRENDING_PAGE: 'SYNC_POPULAR_PAGE',
  SYNC_FAVORITE_PAGE_POPULAR: 'SYNC_FAVORITE_PAGE_POPULAR',
  SYNC_FAVORITE_PAGE_TRENDING: 'SYNC_FAVORITE_PAGE_TRENDING',
}
